version: '3.8'
services:
  db:
    image: ${DATABASE_IMAGE_NAME}
    container_name: ${DATABASE_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DABATASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - ${DATABASE_VOLUME_PATH}:${DATABASE_CONTAINER_VOLUME_PATH}
    ports:
      - ${DATABASE_PORT}:${DATABASE_CONTAINER_PORT}